In [2]:
import numpy as np

In [17]:
ar = np.array([1,2,3,4,5,6,7,8,9])
print(ar)

[1 2 3 4 5 6 7 8 9]


In [18]:
print(ar[0])

1


In [19]:
ar[0::2]

array([1, 3, 5, 7, 9])

In [21]:
ar1 = ar.reshape(3,3)

In [22]:
ar1.shape

(3, 3)

In [25]:
print(ar1[0,1])

2


In [29]:
print(ar1+10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [30]:
print(ar1*10)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [31]:
print(ar1**2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [32]:
print(ar1.sum())

45


In [33]:
print(ar1.mean())

5.0


In [34]:
print(ar1.max())

9
